services:
  php:
    image: php:8.2-apache
    container_name: tomtroc_php
    volumes:
      - ./app:/var/www/html
      - ./config:/var/www/config
    ports:
      - "88:80"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: tomtroc_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: tomtroc
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: tomtroc_phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: 123456789
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  db_data:
