version: '3.8'

services:
  php:
    container_name: dev8
    image: studizz/dev8
    ports:
      - "88:80"
    volumes:
      - /home/mael/work/studizz/php:/var/www/html
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: tomtroc
    volumes:
      - /home/mael/work/docker/volumes/mysql:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: 123456789
    ports:
      - "8080:80"
    depends_on:
      - mysql